# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.21
supported_versions=1.21.1
yarn_mappings=1.21+build.2
enabled_platforms=fabric,neoforge

# Mod Properties
mod_version=5.1.3-1.21.1
maven_group=eu.midnightdust.blur
archives_base_name=blur
release_type=
curseforge_id=
modrinth_id=

# Modloaders
fabric_loader_version=0.16.10
fabric_api_version=0.115.0+1.21.1

neoforge_version=21.0.167
yarn_mappings_patch_neoforge_version = 1.21+build.4

# Libraries
midnightlib_version = 1.6.8+1.21.1
modmenu_version = 11.0.2
